version: "3.2"

services:

  migrations:
    command: bash -c "cd /mindsdb && python ./mindsdb/migrations/migrate.py"

    <<: &globalSettings
      build:
        context: ../
        dockerfile: ./docker/mindsdb.Dockerfile
      volumes:
        - type: bind
          source: ../
          target: /mindsdb
      environment:
        MINDSDB_STORAGE_DIR: "/mindsdb/var"

  mindsdb:
    # Copy global settings from migration above
    <<: *globalSettings
    restart: always
    ports:
      - '47334:47334'
      - '47335:47335'
    command: bash -c "cd /mindsdb && python -m mindsdb"
    environment:
      MINDSDB_ML_SERVICE_HOST: "ml_service"
      MINDSDB_ML_SERVICE_PORT: 5000
      MINDSDB_DOCKER_ENV: "True"
      MINDSDB_STORAGE_DIR: "/mindsdb/var"
      MINDSDB_DB_SERVICE_HOST: "db_service"
      MINDSDB_DB_SERVICE_PORT: 5000
      FLASK_DEBUG: "1"
      FLASK_ENV: "development"
      FLASK_APP: "/mindsdb/mindsdb/__main__.py"
      SEPARATE_MIGRATIONS: "1"
    depends_on:
      - migrations
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:47334/api/util/ping"]
      interval: 30s
      timeout: 4s
      retries: 100

        # mysql_db:
        #   image: "mindsdb/mysql-handler-test"
        #   ports:
        #     - 3307:3306
        #   command: --secure-file-priv=/
        #   environment:
        #     MYSQL_ROOT_PASSWORD: "supersecret"
        #     MYSQL_DATABASE: "test"
        #   healthcheck:
        #     test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
        #     interval: 120s
        #     timeout: 4s
        #     retries: 100


  ml_service:
    build:
      context: ../
      dockerfile: ./docker/ml_handler.Dockerfile
    ports:
      - 5001:5000
    depends_on:
      - mindsdb
    environment:
      # have to share mindsdb database, because it doens't work without it
      MINDSDB_STORAGE_DIR: "/mindsdb/var"

  db_service:
    build:
      context: ../
      dockerfile: ./docker/db_handler.Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mindsdb
      - mysql_db

    volumes:
      - type: bind
        source: ../
        target: /mindsdb
    environment:
      MINDSDB_STORAGE_DIR: "/mindsdb/var"

    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 120s
      timeout: 4s
      retries: 100
